### ISSUE TITLE
Week 9: Presentation Figures and Details

### ISSUE THREAD

**Issue by kobelschool** [marlinfiggins/spelhouse-drp-2023#12]
Notes:
April 27 Title submission
May 2nd Pre Presentation meeting
Desired figures for presentation (perhaps more to come):

- [ ] SIR figures to assist in explaining the choice of basic reproduction number as mean for offspring distributions
- [ ] Plots comparing Poisson vs Negative Binomial distributions on most developed models (I.E. model with initial population and immunity)
- [ ] SIR model graph to compare with branching process figures

(Push notebook for figures with "@marlinfiggins" in pull requests 1 at a time for review)

**Comment by kobelschool** [comment]
@marlinfiggins I am struggling. I am not really sure what figures/plots to make. You mentioned just running the presentation over and over until a narrative forms correct? Would that be a more guiding process? Because trying to make figures feels really aimless at the moment.

**Comment by marlinfiggins** [comment]
Yes, I think that's a much better guiding process! Figures exist to communicate a message once you understand what message you want to communicate on each slide figuring out which figure to make / put there will be a bit easier.

You might want to consider making a bullet pointed list of what you want folks to take away for each individual slide if you're struggling with the narrative as well. Sometimes writing down your thoughts like this might give you a bit of clarity.
