### ISSUE TITLE
Week 2: Further Readings

### ISSUE THREAD

**Issue by kobelschool** [marlinfiggins/spelhouse-drp-2023#5]
- Reading chapter 1 of the epidemiology book: Really interested in the jacobian analysis of the ODE the author uses would love to discuss that further
- Phylo tree of Ebola looks interesting in terms of how the virus seems to mutate rapidly and with longevity in particular areas as opposed to others. As a side note, I assume a lack of mutations in a virus doesn't directly imply a lack of further spread, but I would guess are the two factors are correlated?

**Comment by marlinfiggins** [comment]
Sounds good. We'll plan to discuss chapter 1 of [Mathematical Epidemiology](https://g.co/kgs/Z8At9C) tomorrow focusing on analyzing stability in ODE models.

As for the Ebola tree, we can talk more about this tomorrow and see if there's anything interesting we can see from there. Also, we can discuss the relationship between mutation and transmission.
